# Leitura GCS

In [ ]:
import json
import pandas as pd
from unidecode import unidecode
from pyspark import SparkContext, SparkConf
from pyspark.sql import SparkSession, functions as f

In [ ]:
sc = SparkContext.getOrCreate(conf = SparkConf())
spark = SparkSession.builder.appName("gabriel.paiva").getOrCreate()
spark.conf.set('spark.sql.repl.eagerEval.enabled', True)
spark.conf.set("spark.sql.execution.arrow.enabled","true")

In [3]:
path = 'gs://cnt-landing-zone/DATA_FILE/cnt_ora_0000_kill_vendas'

In [4]:
file = spark \
    .read \
    .parquet(path)

In [12]:
df = file.where(
    file['dat_chave'].between(f.date_sub(f.current_date(), 16), f.date_sub(f.current_date(), 1))
).withColumn(
    'index', f.monotonically_increasing_id() + 1
)

In [13]:
df.limit(5).toPandas()

,COD_ESTAB,NRO_SEQ_VENDA,NRO_PDV,DAT_VENDA,HOR_MIN_VENDA,MLA_FUNC_OPER,MLA_FUNC_VENDEDOR,COD_MOD_VENDA,COD_PLANO,IDT_STATUS_VENDA,...,NRO_COMPROVANTE,IDC_PROCESSADO_RET,NRO_DIAS_PRZ_MEDIO,VLR_FRETE,IDT_OPCAO_SPORTCAR,CHAVE_P2K,TIP_VENDA,DAT_CARGA,dat_chave,index
0,0234,1409896.0000000000,111.0000000000,2022-03-05,13:32:58,97469,43544,PK,999.0000000000,F,...,None,None,0.00,0.00,None,02340000580011105032022,None,2022-03-10 05:06:20,2022-03-05,1
1,0071,2898352.0000000000,528.0000000000,2022-03-05,14:33:50,88006,23949,PK,999.0000000000,F,...,None,None,0.00,0.00,None,00710001340052805032022,None,2022-03-10 05:06:20,2022-03-05,2
2,0241,1204517.0000000000,121.0000000000,2022-03-05,14:31:22,87749,32167,PK,999.0000000000,F,...,None,None,0.00,0.00,None,02410000200012105032022,None,2022-03-10 05:06:20,2022-03-05,3
3,0076,2329553.0000000000,121.0000000000,2022-03-05,14:33:12,95295,28736,PK,999.0000000000,F,...,None,None,0.00,0.00,None,00760000700012105032022,None,2022-03-10 05:06:20,2022-03-05,4
4,0085,1976780.0000000000,528.0000000000,2022-03-05,14:32:30,96854,23171,PK,999.0000000000,F,...,None,None,0.00,0.00,None,00850001080052805032022,None,2022-03-10 05:06:20,2022-03-05,5